services:
  db:
    image: postgres:15
    container_name: deribit_db
    environment:
      POSTGRES_DB: deribit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: deribit_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    container_name: deribit_web
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: deribit_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_URL: redis://redis:6379/0
      DERIBIT_BASE_URL: https://www.deribit.com/api/v2
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery:
    build: .
    container_name: deribit_celery
    depends_on:
      - db
      - redis
      - web
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: deribit_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_URL: redis://redis:6379/0
      DERIBIT_BASE_URL: https://www.deribit.com/api/v2
    volumes:
      - .:/app
    command: celery -A app.tasks.celery_app worker --loglevel=info

  celery-beat:
    build: .
    container_name: deribit_celery_beat
    depends_on:
      - db
      - redis
      - celery
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: deribit_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_URL: redis://redis:6379/0
      DERIBIT_BASE_URL: https://www.deribit.com/api/v2
    volumes:
      - .:/app
    command: celery -A app.tasks.celery_app beat --loglevel=info

volumes:
  postgres_data:
  redis_data: